/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author estud
 */
public class VistaPrincipalDirector extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipalDirector.class.getName());

    /**
     * Creates new form vistaPrincipal
     */
    public VistaPrincipalDirector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        escritorio = new javax.swing.JDesktopPane();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuAgregarDemerito = new javax.swing.JMenuItem();
        menuAgregarMerito = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBuscar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuGrado = new javax.swing.JMenuItem();
        menuEncargado = new javax.swing.JMenuItem();
        menuDocente = new javax.swing.JMenuItem();
        menuAlumno = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        escritorio.setLayer(btnCerrarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu2.setText("Agregar Demeritos");

        menuAgregarDemerito.setText("Agregar Demerito");
        jMenu2.add(menuAgregarDemerito);

        menuAgregarMerito.setText("Agregar Merito");
        menuAgregarMerito.addActionListener(this::menuAgregarMeritoActionPerformed);
        jMenu2.add(menuAgregarMerito);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        menuBuscar.setText("Buscar");
        menuBuscar.addActionListener(this::menuBuscarActionPerformed);
        jMenu3.add(menuBuscar);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Configuracion");

        menuGrado.setText("Ver Grado");
        menuGrado.addActionListener(this::menuGradoActionPerformed);
        jMenu1.add(menuGrado);

        menuEncargado.setText("Ver Encargado");
        menuEncargado.addActionListener(this::menuEncargadoActionPerformed);
        jMenu1.add(menuEncargado);

        menuDocente.setText("Ver Docente");
        jMenu1.add(menuDocente);

        menuAlumno.setText("Agregar Alumno");
        menuAlumno.addActionListener(this::menuAlumnoActionPerformed);
        jMenu1.add(menuAlumno);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGradoActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuAgregarMeritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarMeritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAgregarMeritoActionPerformed

    private void menuEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEncargadoActionPerformed

    private void menuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAlumnoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    public javax.swing.JMenuItem menuAgregarDemerito;
    public javax.swing.JMenuItem menuAgregarMerito;
    public javax.swing.JMenuItem menuAlumno;
    public javax.swing.JMenuItem menuBuscar;
    public javax.swing.JMenuItem menuDocente;
    public javax.swing.JMenuItem menuEncargado;
    public javax.swing.JMenuItem menuGrado;
    // End of variables declaration//GEN-END:variables
}
